x-build-app: &build-app
  context: .
  dockerfile: Dockerfile.app

services:
  appseed-app:
    container_name: appseed-app
    # platform: linux/amd64
    restart: always
    build: *build-app
    image: appseed-app:latest
    ports:
      - "5005:5005"
      - "5006:5005"
    networks:
      - db-network
    volumes:
      - media-data:/app/media
    env_file:
      - .env
    command: >
      sh -c "
        python manage.py collectstatic --no-input --clear
        python manage.py makemigrations
        python manage.py migrate
        gunicorn --config gunicorn-cfg.py core.wsgi"
    depends_on:
      - appseed-db
      - appseed-redis

  appseed-celery:
    container_name: appseed-celery
    restart: always
    image: appseed-app:latest
    ports:
      - "5007:5005"
    env_file:
      - .env
    networks:
      - db-network
    depends_on:
      - appseed-app
    command: >
      sh -c "celery -A core worker -l info -B"

  appseed-redis:
    image: redis:7.0.12
    container_name: appseed-redis
    command: ["redis-server", "--port", "6379", "--slave-read-only", "no"]
    restart: always
    ports:
      - 6379:6379
    networks:
      - db-network

  appseed-db:
    container_name: appseed-db
    # platform: linux/amd64
    restart: always
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
volumes:
  postgres-data:
  media-data:
