name: AppSeed v2 - Dev

on:
  push:
    branches:
      - development__
    # paths-ignore:
    #   - "docs/source/**"

jobs:
  deployment:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        timeout-minutes: 120
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          port: ${{ secrets.PORT }}
          timeout: 120m
          command_timeout: 120m
          script: |
            cd ~/appseed-dev
            git pull origin development
            docker stop appseed-app-dev
            docker system prune -af
            cd ~/appseed-dev
            cp -r media/* /var/lib/docker/volumes/appseed-dev_media-data/_data/
            docker compose -f docker-compose-dev.yml build --no-cache && docker compose -f docker-compose-dev.yml up -d appseed-app-dev
