name: AppSeed v2 - Nginx Prod

on:
  push:
    branches:
      - main
    paths:
      - "nginx/prod/**"

jobs:
  deployment:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        timeout-minutes: 120
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          port: ${{ secrets.PORT }}
          timeout: 120m
          command_timeout: 120m
          script: |
            cd ~/appseed-v2
            git pull origin main
            cp nginx/prod/app-generator /etc/nginx/sites-enabled/app-generator
            nginx -t
            systemctl reload nginx
